name: Test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./run_tests.sh
      - name: Show logs
        if: ${{ failure() }}
        run: docker-compose -f ./docker-compose.test.yml logs
